force-app/main/default/objects/Campaign_Prize_Item__c/Campaign_Prize_Item__c.object-meta.xml
<CustomObject>
    <label>Campaign Prize Item</label>
    <nameField>
        <label>Campaign Prize Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Prize Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Prize_Item__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Loot_Campaign__c</referenceTo>
    <relationshipLabel>Campaign Prize Items</relationshipLabel>
    <relationshipName>Campaign_Prize_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_Prize_Item__c/fields/Prize__c.field-meta.xml
<CustomField>
    <fullName>Prize__c</fullName>
    <label>Prize</label>
    <referenceTo>Prize__c</referenceTo>
    <relationshipLabel>Campaign Prize Items</relationshipLabel>
    <relationshipName>Campaign_Prize_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loot_Campaign__c/Loot_Campaign__c.object-meta.xml
<CustomObject>
    <label>Loot Campaign</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>Loot Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loot Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loot_Campaign__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is the Campaign Active?</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loot_Campaign__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East and West</fullName>
            </value>
            <value>
                <fullName>East and Central</fullName>
            </value>
            <value>
                <fullName>West and Central</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Participant_Email__c.field-meta.xml
<CustomField>
    <fullName>Participant_Email__c</fullName>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>East and West</fullName>
            </value>
            <value>
                <fullName>East and Central</fullName>
            </value>
            <value>
                <fullName>West and Central</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prize__c/Prize__c.object-meta.xml
<CustomObject>
    <label>Prize</label>
    <nameField>
        <label>Prize Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prizes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prize__c/fields/Prize_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Prize_Image_URL__c</fullName>
    <label>Prize Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Selected_Loot_Items__c/Selected_Loot_Items__c.object-meta.xml
<CustomObject>
    <label>Selected Loot Item</label>
    <nameField>
        <displayFormat>SLI-{000000}</displayFormat>
        <label>Selected Loot Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Loot Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Selected_Loot_Items__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Selected Loot Items</relationshipLabel>
    <relationshipName>Selected_Loot_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Selected_Loot_Items__c/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <label>Preference</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Selected_Loot_Items__c/fields/Prize__c.field-meta.xml
<CustomField>
    <fullName>Prize__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prize</label>
    <referenceTo>Campaign_Prize_Item__c</referenceTo>
    <relationshipLabel>Selected Loot Items</relationshipLabel>
    <relationshipName>Selected_Loot_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LootController.cls
public with sharing class LootController {
    
    @AuraEnabled(cacheable=true)
    public static List<Campaign_Prize_Item__c> getCampaignPrizeItems(String userId){
        List<User> currUser = [SELECT Id, Name, Email, Region__c FROM User WHERE Id =:userId];
        String currUser_Region = currUser[0].Region__c;
        String currUser_Email = currUser[0].Email;
        List<Campaign_Prize_Item__c> availablePrizes = new List<Campaign_Prize_Item__c>();
      
        if(currUser.size()>0 && !''.equals(currUser_Region) && currUser_Region!=null){
            List<Loot_Campaign__c> activeLootCampaigns = [SELECT Id, Name, Active__c, Region__c FROM Loot_Campaign__c WHERE Region__c = :currUser_Region AND Active__c=true];
            if(activeLootCampaigns.size()>0){
               Loot_Campaign__c currLootCampaign = activeLootCampaigns[0];
               List<Selected_Loot_Items__c> chosenItems = new List<Selected_Loot_Items__c>();
               chosenItems = [SELECT Id,Name, Participant__c, Participant__r.Participant_Email__c, Preference__c, Prize__c, Prize__r.Campaign__c,  Prize__r.Name FROM Selected_Loot_Items__c WHERE Participant__r.Participant_Email__c = :currUser_Email AND Prize__r.Campaign__c = :currLootCampaign.Id];
               availablePrizes = [SELECT Id, Name, Prize__c, Prize__r.Name, Prize__r.Prize_Image_URL__c, Campaign__c FROM Campaign_Prize_Item__c WHERE Campaign__c =:currLootCampaign.Id];
               System.debug(availablePrizes);
            }
        }
        return availablePrizes;
    }

    @AuraEnabled
    public static List<Selected_Loot_Items__c> getSelectedLootItems(String userId){
        List<User> currUser = [SELECT Id, Name, Email, Region__c FROM User WHERE Id =:userId];
        List<Selected_Loot_Items__c> selectedItems = new List<Selected_Loot_Items__c>();
        if(currUser.size()>0){
            String currUser_Region = currUser[0].Region__c;
            String currUser_Email = currUser[0].Email;
            if(!''.equals(currUser_Region) && currUser_Region!=null){
            List<Loot_Campaign__c> activeLootCampaigns = [SELECT Id, Name, Active__c, Region__c FROM Loot_Campaign__c WHERE Region__c = :currUser_Region AND Active__c=true];
                if(activeLootCampaigns.size()>0){
                    Loot_Campaign__c currLootCampaign = activeLootCampaigns[0];
                    selectedItems = [SELECT Id, Prize__c, Prize__r.Campaign__c, Preference__c  FROM Selected_Loot_Items__c WHERE Participant__r.Participant_Email__c = :currUser_Email AND Prize__r.Campaign__c = :currLootCampaign.Id ORDER BY Preference__c ASC ];
                }
            }
        }
        return selectedItems;
    }

    @AuraEnabled
    public static String createParticipant(String userId){
        String message = '';
        List<User> currUser = [SELECT Id, Name, Email, Region__c FROM User WHERE Id =:userId];
        String currUser_Email = currUser[0].Email;
        String currUser_Region = currUser[0].Region__c;
        String currUser_Name = currUser[0].Name;
        List<Participant__c> participants = [SELECT Id, Participant_Email__c FROM Participant__c WHERE Participant_Email__c =:currUser_Email];
        if(participants.size()<=0){
            Participant__c participant = new Participant__c();
            participant.Participant_Email__c = currUser_Email;
            participant.Region__c = currUser_Region;
            participant.Name = currUser_Name;
            message = 'Participant Created';
            insert participant;
        }else {
            message = 'Participant exists';
        }

        return message;
    }

    @AuraEnabled
    public static String createSelectedLootItems(String selectedPrizes, String userId, String campaignId){
        String message = 'No action taken';
        List<User> currUser = [SELECT Id, Name, Email, Region__c FROM User WHERE Id =:userId];
        String currUser_Email = currUser[0].Email;
        
        List<Participant__c> participant = [SELECT Id, Participant_Email__c FROM Participant__c WHERE Participant_Email__c =:currUser_Email];
        
        List<Selected_Loot_Items__c> slis = new List<Selected_Loot_Items__c>();
        
        List<Selected_Loot_Items__c> deleteSlis = new List<Selected_Loot_Items__c>();

        List<Selected_Loot_Items__c> updateSlis = new List<Selected_Loot_Items__c>();
        
        List<String> prizeIds = selectedPrizes.split(',');
        
        if(prizeIds.size()>0 && participant.size()>0){
            List<Selected_Loot_Items__c> existingSlis = [SELECT Id, Prize__c,Preference__c FROM Selected_Loot_Items__c WHERE Prize__r.Campaign__c=:campaignId ORDER BY Preference__c ASC];
            List<String> existingIds = new List<String>();
            Integer count = 1;

            for(Selected_Loot_Items__c esli : existingSlis){
                if(prizeIds.indexOf(esli.Prize__c)==-1){
                    deleteSlis.add(esli);
                } else{
                    existingIds.add(esli.Prize__c);
                }
            }
            for(Integer i=0;i<prizeIds.size();i++){
                if(existingIds.indexOf(prizeIds[i])==-1 && !''.equals(prizeIds[i])){
                    Selected_Loot_Items__c sli = new Selected_Loot_Items__c();
                    sli.Participant__c = participant[0].Id;
                    sli.Preference__c = i+1;
                    sli.Prize__c = prizeIds[i];
                    slis.add(sli);
                }else{
                    for(Selected_Loot_Items__c esli : existingSlis){
                        if(!''.equals(prizeIds[i]) &&  prizeIds[i] == esli.Prize__c){    
                            esli.Preference__c = i+1;
                            updateSlis.add(esli);
                            break;
                        }
                    }
                }
            }
            if(slis.size()>0){
                insert slis;
                message = 'Selected Loot Items inserted';
            }
            if(updateSlis.size()>0){
                update updateSlis;
                message = message+' Items Updated As Well';
            }
            if(deleteSlis.size()>0){
                delete deleteSlis;
                message = message+' Items Deleted As Well';
            }
        }
        return message;
    }

}